apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: devlift-user
  POSTGRES_PASSWORD: 5482p]G5we3q
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: devlift-root
  POSTGRES_NON_ROOT_PASSWORD: Cr0Y(TC2iQ69